[package]
name = "chdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chdb-bindings-rs = "0.1.5"
enum2str = "0.1.9"
